import { generatedAssets } from "./generated/assets.generated";
import { generatedCountryLaw } from "./generated/countriesLaw.generated";
import { generatedCrimes } from "./generated/crimes.generated";
import { generatedFameActivities, generatedSocialPlatforms } from "./generated/fameSocial.generated";
import { generatedPets } from "./generated/pets.generated";
import { generatedPrisonActivities } from "./generated/prison.generated";
import { generatedRomanceActivities } from "./generated/romanceFamily.generated";
import { generatedTravelActivities } from "./generated/travelMigration.generated";
import type { P1Catalog } from "./schema";

const zhCN: P1Catalog["locales"]["zh-CN"] = {
  "p1.asset.compact_apartment.name": "紧凑公寓",
  "p1.asset.used_hatchback.name": "二手掀背车",
  "p1.asset.gold_ring.name": "金戒指",
  "p1.asset.practice_guitar.name": "练习吉他",
  "p1.asset.fishing_boat.name": "钓鱼船",
  "p1.asset.small_aircraft.name": "小型飞机",
  "p1.crime.shoplifting.name": "顺手牵羊",
  "p1.crime.pickpocket.name": "扒窃",
  "p1.crime.burglary.name": "入室盗窃",
  "p1.crime.car_theft.name": "盗车",
  "p1.crime.bank_robbery.name": "银行抢劫",
  "p1.crime.fraud.name": "诈骗",
  "p1.prison.appeal.label": "提交上诉",
  "p1.prison.appeal.result": "你递交材料，等待重新审理。",
  "p1.prison.parole.label": "申请假释",
  "p1.prison.parole.result": "你认真陈述改过计划，争取提前释放。",
  "p1.prison.work.label": "参加狱中劳动",
  "p1.prison.work.result": "你完成了当天的劳动，得到少量报酬。",
  "p1.prison.exercise.label": "在院子里锻炼",
  "p1.prison.exercise.result": "你流了一身汗，身体感觉更结实。",
  "p1.fame.interview.label": "接受专访",
  "p1.fame.interview.result": "这次访谈让更多人记住了你。",
  "p1.fame.ad.label": "接商业广告",
  "p1.fame.ad.result": "广告上线后，你收到一笔可观收入。",
  "p1.fame.charity.label": "举办慈善活动",
  "p1.fame.charity.result": "你的善举得到关注，也帮助了需要的人。",
  "p1.fame.scandal_response.label": "回应负面传闻",
  "p1.fame.scandal_response.result": "你谨慎发声，让舆论慢慢降温。",
  "p1.social.short_video.name": "短视频平台",
  "p1.social.photo_feed.name": "照片动态",
  "p1.social.streaming.name": "直播频道",
  "p1.pet.cat.name": "猫",
  "p1.pet.small_dog.name": "小型犬",
  "p1.pet.large_dog.name": "大型犬",
  "p1.pet.parrot.name": "鹦鹉",
  "p1.pet.rabbit.name": "兔子",
  "p1.travel.vacation.label": "安排度假",
  "p1.travel.vacation.result": "旅行让你暂时放下压力，心情更轻松。",
  "p1.travel.honeymoon.label": "蜜月旅行",
  "p1.travel.honeymoon.result": "你们度过了难忘的旅程，关系更亲近。",
  "p1.migration.legal.label": "申请合法移居",
  "p1.migration.legal.result": "你提交材料，开始等待移居审批。",
  "p1.migration.illegal.label": "冒险偷渡",
  "p1.migration.illegal.result": "这条路风险很高，你必须承担后果。",
  "p1.romance.date.label": "约会",
  "p1.romance.date.result": "这次见面让彼此更熟悉。",
  "p1.romance.propose.label": "求婚",
  "p1.romance.propose.result": "你准备好戒指，说出了重要的问题。",
  "p1.family.try_child.label": "尝试要孩子",
  "p1.family.try_child.result": "你们认真讨论家庭计划，期待新的可能。",
  "p1.family.adopt.label": "申请收养",
  "p1.family.adopt.result": "你开始办理收养手续，为新家庭成员做准备。",
  "p1.romance.divorce.label": "办理离婚",
  "p1.romance.divorce.result": "这段关系走到终点，你开始重新整理生活。",
  "p1.family.child_time.label": "陪伴孩子",
  "p1.family.child_time.result": "你花时间陪孩子，让家庭关系更紧密。",
  "p1.log.asset.buy": "你买下了一件资产。",
  "p1.log.asset.sell": "你卖出了一件资产。",
  "p1.log.crime.success": "犯罪得手了。",
  "p1.log.crime.fail": "犯罪失败，你被盯上了。",
  "p1.log.crime.arrest": "你被逮捕并判刑。",
  "p1.log.pet.adopt": "你领养了一只宠物。",
  "p1.log.pet.care": "你照顾了宠物。",
  "p1.log.romance.dating": "你开始了一段恋情。",
  "p1.log.romance.marriage": "你结婚了。",
  "p1.log.romance.divorce": "你结束了一段婚姻。",
  "p1.log.family.pregnancy_start": "家庭迎来了新计划。",
  "p1.log.family.adopt": "你收养了孩子。",
  "p1.log.family.birth": "孩子出生了。",
  "p1.log.prison.release": "你出狱了。",
  "p1.log.prison.year": "你又度过了一年刑期。",
  "p1.log.prison.parole_approved": "假释申请获批。",
  "p1.log.prison.parole_denied": "假释申请被拒。",
  "p1.log.travel.vacation": "你完成了一次旅行。",
  "p1.log.migration.legal.approved": "合法移居申请获批。",
  "p1.log.migration.legal.rejected": "合法移居申请被拒。",
  "p1.log.migration.illegal.success": "你成功越境。",
  "p1.log.migration.illegal.deported": "你被遣返了。",
  "p1.log.migration.illegal.injured": "偷渡途中受伤。",
  "p1.log.fame.unlock": "你开始受到公众关注。",
  "p1.log.social.create": "你创建了社交账号。",
  "p1.log.social.post": "你发布了社交动态。"
};

const enUS: P1Catalog["locales"]["en-US"] = {
  "p1.asset.compact_apartment.name": "Compact Apartment",
  "p1.asset.used_hatchback.name": "Used Hatchback",
  "p1.asset.gold_ring.name": "Gold Ring",
  "p1.asset.practice_guitar.name": "Practice Guitar",
  "p1.asset.fishing_boat.name": "Fishing Boat",
  "p1.asset.small_aircraft.name": "Small Aircraft",
  "p1.crime.shoplifting.name": "Shoplifting",
  "p1.crime.pickpocket.name": "Pickpocketing",
  "p1.crime.burglary.name": "Burglary",
  "p1.crime.car_theft.name": "Car Theft",
  "p1.crime.bank_robbery.name": "Bank Robbery",
  "p1.crime.fraud.name": "Fraud",
  "p1.prison.appeal.label": "File an Appeal",
  "p1.prison.appeal.result": "You submit the paperwork and wait for another review.",
  "p1.prison.parole.label": "Request Parole",
  "p1.prison.parole.result": "You explain your plan to change and ask for early release.",
  "p1.prison.work.label": "Take a Prison Job",
  "p1.prison.work.result": "You complete the shift and earn a small payment.",
  "p1.prison.exercise.label": "Exercise in the Yard",
  "p1.prison.exercise.result": "You work up a sweat and feel a little stronger.",
  "p1.fame.interview.label": "Give an Interview",
  "p1.fame.interview.result": "The interview helps more people remember your name.",
  "p1.fame.ad.label": "Accept an Endorsement",
  "p1.fame.ad.result": "The campaign launches and you receive a solid payday.",
  "p1.fame.charity.label": "Host a Charity Event",
  "p1.fame.charity.result": "Your generosity draws attention and helps people in need.",
  "p1.fame.scandal_response.label": "Respond to Rumors",
  "p1.fame.scandal_response.result": "You choose your words carefully and the backlash cools down.",
  "p1.social.short_video.name": "Short Video Platform",
  "p1.social.photo_feed.name": "Photo Feed",
  "p1.social.streaming.name": "Streaming Channel",
  "p1.pet.cat.name": "Cat",
  "p1.pet.small_dog.name": "Small Dog",
  "p1.pet.large_dog.name": "Large Dog",
  "p1.pet.parrot.name": "Parrot",
  "p1.pet.rabbit.name": "Rabbit",
  "p1.travel.vacation.label": "Plan a Vacation",
  "p1.travel.vacation.result": "The trip gives you a break from stress and lifts your mood.",
  "p1.travel.honeymoon.label": "Take a Honeymoon",
  "p1.travel.honeymoon.result": "You share a memorable trip and grow closer.",
  "p1.migration.legal.label": "Apply to Emigrate",
  "p1.migration.legal.result": "You file the paperwork and begin waiting for approval.",
  "p1.migration.illegal.label": "Attempt an Illegal Crossing",
  "p1.migration.illegal.result": "The route is risky, and you have to live with the consequences.",
  "p1.romance.date.label": "Go on a Date",
  "p1.romance.date.result": "The outing helps you get to know each other better.",
  "p1.romance.propose.label": "Propose Marriage",
  "p1.romance.propose.result": "You prepare the ring and ask the big question.",
  "p1.family.try_child.label": "Try for a Child",
  "p1.family.try_child.result": "You talk through family plans and hope for a new possibility.",
  "p1.family.adopt.label": "Apply to Adopt",
  "p1.family.adopt.result": "You begin the adoption process and prepare for a new family member.",
  "p1.romance.divorce.label": "File for Divorce",
  "p1.romance.divorce.result": "The relationship ends, and you begin sorting out your life again.",
  "p1.family.child_time.label": "Spend Time with Children",
  "p1.family.child_time.result": "You make time for your children and strengthen family bonds.",
  "p1.log.asset.buy": "You bought an asset.",
  "p1.log.asset.sell": "You sold an asset.",
  "p1.log.crime.success": "The crime paid off.",
  "p1.log.crime.fail": "The crime failed, and suspicion rose.",
  "p1.log.crime.arrest": "You were arrested and sentenced.",
  "p1.log.pet.adopt": "You adopted a pet.",
  "p1.log.pet.care": "You cared for your pet.",
  "p1.log.romance.dating": "You started dating someone.",
  "p1.log.romance.marriage": "You got married.",
  "p1.log.romance.divorce": "You ended a marriage.",
  "p1.log.family.pregnancy_start": "Your family made a new plan.",
  "p1.log.family.adopt": "You adopted a child.",
  "p1.log.family.birth": "A child was born.",
  "p1.log.prison.release": "You were released from prison.",
  "p1.log.prison.year": "You served another year in prison.",
  "p1.log.prison.parole_approved": "Your parole request was approved.",
  "p1.log.prison.parole_denied": "Your parole request was denied.",
  "p1.log.travel.vacation": "You completed a trip.",
  "p1.log.migration.legal.approved": "Your legal emigration was approved.",
  "p1.log.migration.legal.rejected": "Your legal emigration was rejected.",
  "p1.log.migration.illegal.success": "You crossed the border successfully.",
  "p1.log.migration.illegal.deported": "You were deported.",
  "p1.log.migration.illegal.injured": "You were injured during the crossing.",
  "p1.log.fame.unlock": "You started drawing public attention.",
  "p1.log.social.create": "You created a social account.",
  "p1.log.social.post": "You posted an update."
};

export const p1Catalog: P1Catalog = {
  locales: {
    "zh-CN": zhCN,
    "en-US": enUS
  },
  assets: generatedAssets,
  crimes: generatedCrimes,
  prisonActivities: generatedPrisonActivities,
  countryLaw: generatedCountryLaw,
  fameActivities: generatedFameActivities,
  socialPlatforms: generatedSocialPlatforms,
  pets: generatedPets,
  travelActivities: generatedTravelActivities,
  romanceActivities: generatedRomanceActivities
};
